//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

public partial class Data_Base_imfEntities2 : ObjectContext
{
    public const string ConnectionString = "name=Data_Base_imfEntities2";
    public const string ContainerName = "Data_Base_imfEntities2";

    #region Constructors

    public Data_Base_imfEntities2()
        : base(ConnectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public Data_Base_imfEntities2(string connectionString)
        : base(connectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public Data_Base_imfEntities2(EntityConnection connection)
        : base(connection, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    #endregion

    #region ObjectSet Properties

    public ObjectSet<Administrateur> Administrateurs
    {
        get { return _administrateurs  ?? (_administrateurs = CreateObjectSet<Administrateur>("Administrateurs")); }
    }
    private ObjectSet<Administrateur> _administrateurs;

    public ObjectSet<Agence> Agences
    {
        get { return _agences  ?? (_agences = CreateObjectSet<Agence>("Agences")); }
    }
    private ObjectSet<Agence> _agences;

    public ObjectSet<Agent_de_credits> Agent_de_credits
    {
        get { return _agent_de_credits  ?? (_agent_de_credits = CreateObjectSet<Agent_de_credits>("Agent_de_credits")); }
    }
    private ObjectSet<Agent_de_credits> _agent_de_credits;

    public ObjectSet<Client> Clients
    {
        get { return _clients  ?? (_clients = CreateObjectSet<Client>("Clients")); }
    }
    private ObjectSet<Client> _clients;

    public ObjectSet<Contact> Contacts
    {
        get { return _contacts  ?? (_contacts = CreateObjectSet<Contact>("Contacts")); }
    }
    private ObjectSet<Contact> _contacts;

    public ObjectSet<Productivite> Productivites
    {
        get { return _productivites  ?? (_productivites = CreateObjectSet<Productivite>("Productivites")); }
    }
    private ObjectSet<Productivite> _productivites;

    public ObjectSet<sysdiagram> sysdiagrams
    {
        get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
    }
    private ObjectSet<sysdiagram> _sysdiagrams;

    public ObjectSet<Utilisateur> Utilisateurs
    {
        get { return _utilisateurs  ?? (_utilisateurs = CreateObjectSet<Utilisateur>("Utilisateurs")); }
    }
    private ObjectSet<Utilisateur> _utilisateurs;

    #endregion
}
